[phases.setup]
nixPkgs = ["nodejs_22"]

[phases.install]
cmds = [
  "npm install -g pnpm@9.12.0",
  "pnpm install --frozen-lockfile"
]

[phases.build]
cmds = ["pnpm --filter @espelmes/api build"]

[start]
cmd = "pnpm --filter @espelmes/api start:prod"
